#just for tac
statistics=true
job=job_master_sa
jobVersion=0.1
date=2026-04-20 225600977
contextName=Default
jobId=_q8VKwDzvEfGgUI28QlsbhQ
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=AUTOMATIZATION
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=